development:
  adapter: postgresql
  database: orari_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: orari_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: orari_production
  pool: 5
  timeout: 5000
