# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64c579b2df3b3c9345224e65cfd5a222e754108b5cd7385253e1cc0bdfc2b23aa6f12000eff6c6806b1f47a99e7409eb15dfd8c5d3c0b0b05fa1012eee533111

test:
  secret_key_base: 18e349f629dc8a3d4492c1c5e87c8a89f0c000e32d22ff7f562e970ad0e107e7adb530fc8271b146bea60314654220a02026954c87ad98984b34fbe6a8da434f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
